name: dairy_track
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  syncfusion_flutter_xlsio: ^21.2.3
  pdf: ^3.10.0
  path_provider: ^2.0.11
  file_picker: ^10.1.2
  open_file: ^3.2.1
  html: ^0.15.0
  image_picker: ^0.8.7
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Tambahkan bagian assets di bawah ini
  assets:
    - assets/images/
