name: dairy_track
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  file_picker: ^10.1.2
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  html: ^0.15.0
  http: ^1.3.0
  image_picker: ^0.8.7
  intl: ^0.18.0
  lottie: ^3.1.2
  open_file: ^3.2.1
  path_provider: ^2.0.11
  pdf: ^3.10.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  syncfusion_flutter_datepicker: ^21.2.10
  syncfusion_flutter_xlsio: ^21.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
