name: dairytrack_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.20.2
  path_provider: ^2.0.15
  shared_preferences: ^2.0.15
  fl_chart: ^1.0.0
  image_picker: ^1.1.2
  open_file: ^3.2.1
  file_picker: ^10.1.9
  permission_handler: ^11.3.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  animate_do: ^4.2.0
  google_maps_flutter: ^2.12.2
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

# Gunakan flutter_icons sebagai key untuk konfigurasi (sesuai dokumentasi)
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21
